AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.2
  CacheRootDirectory: tmp/rubocop_cache
  Exclude:
    - "pkg/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "spec/fixtures/**/*"

# RSpec の describe ブロックは長くなりがちなので spec では無効化する。
Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
